function Report = importfile_Agilent_I_2(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   REPORT = IMPORTFILE(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   REPORT = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   Report = importfile('Report.TXT', 1, 59);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2021/06/07 13:13:54

%% Initialize variables.
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: categorical (%C)
%	column2: text (%s)
%   column3: categorical (%C)
%	column4: categorical (%C)
%   column5: text (%s)
%	column6: text (%s)
%   column7: text (%s)
%	column8: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%4C%8s%3C%2C%8s%11s%11s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r','n','UTF16-LE');
% Skip the BOM (Byte Order Mark).
fseek(fileID, 2, 'bof');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Remove white space around all cell columns.
dataArray{2} = strtrim(dataArray{2});
dataArray{5} = strtrim(dataArray{5});
dataArray{6} = strtrim(dataArray{6});
dataArray{7} = strtrim(dataArray{7});
dataArray{8} = strtrim(dataArray{8});

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

%% Create output variable
Report = table(dataArray{1:end-1}, 'VariableNames', {'Data','FileC','Ch','em','Dat','a2106_Manu','el210604_m','b_LC20210604124647210604_mb000001D'});

